name: Composer Update

on:
  workflow_dispatch: # allows manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # your PHP version
      - name: Install Composer
        run: sudo apt-get install -y composer
      - name: Run Composer Update
        run: composer update
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add composer.lock
          git commit -m "Update Composer dependencies"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
